FROM python:3.13-slim

WORKDIR /app
COPY requirements.txt .

RUN apt-get update && apt-get install -y netcat-traditional && \
    pip install --no-cache-dir -r requirements.txt

COPY . .
RUN chmod +x start.sh

EXPOSE 7000

CMD [ "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7000", "--reload" ]
